# https://github.com/golangci/golangci-lint#config-file

issues:
  exclude:
    - Using the variable on range scope .* in function literal

  exclude-rules:
    - path: _test\.go
      text: .*do not define dynamic errors.*

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - errcheck
    - errorlint
    - gosec
    - nilerr
    - noctx
    - exportloopref
    - staticcheck
    - cyclop
    - gocyclo
    - funlen
    - nestif
    - goerr113
    - gocritic
    - bodyclose
    - prealloc
    - structcheck
    - wsl
    - makezero
    - deadcode
    - unparam
    - unused
    - varcheck
  fast: false